### ISSUE TITLE
Change endpoints to accept following parameters

### ISSUE THREAD

**Issue by GauteR** [nlbdev/service-saxon#1]
> source: post or abspath
> xslt: post or abspath - build json every time
> output: abspath (optional)
> report: abspath (optional)
> parameter response: enten "output" eller "report"

**Comment by josteinaj** [comment]
Det bør nok også være støtte for alle invocation options fra transform-funksjonen:

https://www.saxonica.com/saxon-js/documentation2/index.html#!api/transform

Det kan f.eks. være så enkelt som en "invocation-options"-parameter som er et JSON-objekt som videresendes til transform-funksjonen.
